/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_etudiants1 (void)
{
  GtkWidget *gestion_etudiants1;
  GtkWidget *fixed2;
  GtkWidget *entry3;
  GtkWidget *treeview1;
  GtkWidget *eventbox7;
  GtkWidget *label3;
  GtkWidget *eventbox8;
  GtkWidget *button15;
  GtkWidget *image14;
  GtkWidget *eventbox9;
  GtkWidget *button3;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label5;
  GtkWidget *eventbox10;
  GtkWidget *button4;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label6;
  GtkWidget *eventbox11;
  GtkWidget *button5;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label7;
  GtkWidget *eventbox12;
  GtkWidget *button6;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label8;
  GtkWidget *image15;

  gestion_etudiants1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_etudiants1), _("gestion_etudiants1"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_etudiants1), fixed2);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 352, 240);
  gtk_widget_set_size_request (entry3, 112, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 472, 200);
  gtk_widget_set_size_request (treeview1, 504, 248);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox7, 280, 200);
  gtk_widget_set_size_request (eventbox7, 184, 32);

  label3 = gtk_label_new (_("Recherche par matricule"));
  gtk_widget_show (label3);
  gtk_container_add (GTK_CONTAINER (eventbox7), label3);
  gtk_widget_set_size_request (label3, 184, 32);
  GTK_WIDGET_SET_FLAGS (label3, GTK_CAN_FOCUS);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox8, 296, 240);
  gtk_widget_set_size_request (eventbox8, 48, 32);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_container_add (GTK_CONTAINER (eventbox8), button15);
  gtk_widget_set_size_request (button15, 48, 32);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_container_add (GTK_CONTAINER (button15), image14);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox9, 984, 224);
  gtk_widget_set_size_request (eventbox9, 96, 32);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (eventbox9), button3);
  gtk_widget_set_size_request (button3, 96, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button3), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox10, 984, 280);
  gtk_widget_set_size_request (eventbox10, 96, 32);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (eventbox10), button4);
  gtk_widget_set_size_request (button4, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button4), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox11, 984, 336);
  gtk_widget_set_size_request (eventbox11, 96, 32);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (eventbox11), button5);
  gtk_widget_set_size_request (button5, 96, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button5), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox12, 984, 392);
  gtk_widget_set_size_request (eventbox12, 96, 32);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (eventbox12), button6);
  gtk_widget_set_size_request (button6, 96, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button6), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox5), label8, FALSE, FALSE, 0);

  image15 = create_pixmap (gestion_etudiants1, "12905.png");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed2), image15, 0, 0);
  gtk_widget_set_size_request (image15, 1080, 576);

  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_etudiants1, gestion_etudiants1, "gestion_etudiants1");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, button15, "button15");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, image14, "image14");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, button3, "button3");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, label5, "label5");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, button4, "button4");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, label6, "label6");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, button5, "button5");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, button6, "button6");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, label8, "label8");
  GLADE_HOOKUP_OBJECT (gestion_etudiants1, image15, "image15");

  return gestion_etudiants1;
}

GtkWidget*
create_gestion_etudiants2 (void)
{
  GtkWidget *gestion_etudiants2;
  GtkWidget *fixed3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *eventbox13;
  GtkWidget *sortie;
  GtkWidget *eventbox14;
  GtkWidget *button11;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label27;
  GtkWidget *eventbox15;
  GtkWidget *button7;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label14;
  GtkWidget *eventbox16;
  GtkWidget *button12;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label29;
  GtkWidget *eventbox23;
  GtkWidget *label21;
  GtkWidget *eventbox24;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *eventbox25;
  GtkWidget *radiobutton2;
  GtkWidget *eventbox26;
  GtkWidget *combobox2;
  GtkWidget *eventbox27;
  GtkWidget *label12;
  GtkWidget *eventbox28;
  GtkWidget *label13;
  GtkWidget *eventbox29;
  GtkWidget *label11;
  GtkWidget *eventbox30;
  GtkWidget *label10;
  GtkWidget *eventbox31;
  GtkWidget *label9;
  GtkWidget *eventbox32;
  GtkWidget *label19;
  GtkWidget *eventbox33;
  GtkWidget *label18;
  GtkWidget *eventbox34;
  GtkWidget *label17;
  GtkWidget *eventbox35;
  GtkWidget *label16;
  GtkWidget *eventbox36;
  GtkWidget *checkbutton1;
  GtkWidget *eventbox37;
  GtkWidget *label28;
  GtkWidget *image16;

  gestion_etudiants2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_etudiants2), _("gestion_etudiants2"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (gestion_etudiants2), fixed3);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 136, 40);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 136, 80);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 136, 120);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed3), entry7, 136, 160);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed3), jour, 64, 344);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed3), mois, 184, 344);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (1, 2021, 2022, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed3), annee, 304, 344);
  gtk_widget_set_size_request (annee, 60, 27);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox13, 160, 432);
  gtk_widget_set_size_request (eventbox13, 49, 17);

  sortie = gtk_label_new ("");
  gtk_widget_show (sortie);
  gtk_container_add (GTK_CONTAINER (eventbox13), sortie);
  gtk_widget_set_size_request (sortie, 49, 17);

  eventbox14 = gtk_event_box_new ();
  gtk_widget_show (eventbox14);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox14, 16, 400);
  gtk_widget_set_size_request (eventbox14, 96, 32);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_container_add (GTK_CONTAINER (eventbox14), button11);
  gtk_widget_set_size_request (button11, 96, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button11), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox10), label27, FALSE, FALSE, 0);

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox15, 136, 400);
  gtk_widget_set_size_request (eventbox15, 88, 32);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (eventbox15), button7);
  gtk_widget_set_size_request (button7, 88, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button7), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox6), label14, FALSE, FALSE, 0);

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox16, 248, 400);
  gtk_widget_set_size_request (eventbox16, 96, 32);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_container_add (GTK_CONTAINER (eventbox16), button12);
  gtk_widget_set_size_request (button12, 96, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button12), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox11), label29, FALSE, FALSE, 0);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox23, 64, 248);
  gtk_widget_set_size_request (eventbox23, 49, 17);

  label21 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label21);
  gtk_container_add (GTK_CONTAINER (eventbox23), label21);
  gtk_widget_set_size_request (label21, 49, 17);

  eventbox24 = gtk_event_box_new ();
  gtk_widget_show (eventbox24);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox24, 128, 248);
  gtk_widget_set_size_request (eventbox24, 80, 24);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton1);
  gtk_container_add (GTK_CONTAINER (eventbox24), radiobutton1);
  gtk_widget_set_size_request (radiobutton1, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox25, 224, 248);
  gtk_widget_set_size_request (eventbox25, 80, 24);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton2);
  gtk_container_add (GTK_CONTAINER (eventbox25), radiobutton2);
  gtk_widget_set_size_request (radiobutton2, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox26, 136, 208);
  gtk_widget_set_size_request (eventbox26, 56, 24);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_container_add (GTK_CONTAINER (eventbox26), combobox2);
  gtk_widget_set_size_request (combobox2, 56, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("4"));

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox27, 56, 208);
  gtk_widget_set_size_request (eventbox27, 64, 24);

  label12 = gtk_label_new (_("Niveau"));
  gtk_widget_show (label12);
  gtk_container_add (GTK_CONTAINER (eventbox27), label12);
  gtk_widget_set_size_request (label12, 64, 24);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox28, 16, 160);
  gtk_widget_set_size_request (eventbox28, 112, 24);

  label13 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label13);
  gtk_container_add (GTK_CONTAINER (eventbox28), label13);
  gtk_widget_set_size_request (label13, 112, 24);

  eventbox29 = gtk_event_box_new ();
  gtk_widget_show (eventbox29);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox29, 16, 120);
  gtk_widget_set_size_request (eventbox29, 112, 24);

  label11 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label11);
  gtk_container_add (GTK_CONTAINER (eventbox29), label11);
  gtk_widget_set_size_request (label11, 112, 24);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox30, 24, 80);
  gtk_widget_set_size_request (eventbox30, 104, 24);

  label10 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label10);
  gtk_container_add (GTK_CONTAINER (eventbox30), label10);
  gtk_widget_set_size_request (label10, 104, 24);

  eventbox31 = gtk_event_box_new ();
  gtk_widget_show (eventbox31);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox31, 32, 40);
  gtk_widget_set_size_request (eventbox31, 96, 24);

  label9 = gtk_label_new (_("Nom"));
  gtk_widget_show (label9);
  gtk_container_add (GTK_CONTAINER (eventbox31), label9);
  gtk_widget_set_size_request (label9, 96, 24);

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox32, 256, 352);
  gtk_widget_set_size_request (eventbox32, 49, 17);

  label19 = gtk_label_new (_("anne\303\251 :"));
  gtk_widget_show (label19);
  gtk_container_add (GTK_CONTAINER (eventbox32), label19);
  gtk_widget_set_size_request (label19, 49, 17);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox33, 136, 352);
  gtk_widget_set_size_request (eventbox33, 49, 17);

  label18 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label18);
  gtk_container_add (GTK_CONTAINER (eventbox33), label18);
  gtk_widget_set_size_request (label18, 49, 17);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox34, 16, 352);
  gtk_widget_set_size_request (eventbox34, 49, 17);

  label17 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label17);
  gtk_container_add (GTK_CONTAINER (eventbox34), label17);
  gtk_widget_set_size_request (label17, 49, 17);

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox35, 16, 312);
  gtk_widget_set_size_request (eventbox35, 144, 25);

  label16 = gtk_label_new (_("Date d'inscription :"));
  gtk_widget_show (label16);
  gtk_container_add (GTK_CONTAINER (eventbox35), label16);
  gtk_widget_set_size_request (label16, 144, 25);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox36, 144, 280);
  gtk_widget_set_size_request (eventbox36, 118, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Handicap\303\251"));
  gtk_widget_show (checkbutton1);
  gtk_container_add (GTK_CONTAINER (eventbox36), checkbutton1);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  eventbox37 = gtk_event_box_new ();
  gtk_widget_show (eventbox37);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox37, 16, 280);
  gtk_widget_set_size_request (eventbox37, 104, 24);

  label28 = gtk_label_new (_("Etat de sant\303\251"));
  gtk_widget_show (label28);
  gtk_container_add (GTK_CONTAINER (eventbox37), label28);
  gtk_widget_set_size_request (label28, 104, 24);

  image16 = create_pixmap (gestion_etudiants2, "maison.png");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed3), image16, 0, 0);
  gtk_widget_set_size_request (image16, 376, 448);

  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_etudiants2, gestion_etudiants2, "gestion_etudiants2");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, jour, "jour");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, mois, "mois");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, annee, "annee");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, sortie, "sortie");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, button11, "button11");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, image10, "image10");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, button7, "button7");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, button12, "button12");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, image11, "image11");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label29, "label29");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label12, "label12");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label11, "label11");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label10, "label10");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label9, "label9");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, eventbox37, "eventbox37");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, label28, "label28");
  GLADE_HOOKUP_OBJECT (gestion_etudiants2, image16, "image16");

  return gestion_etudiants2;
}

